config/routes.rb
Rails.application.routes.draw do
  root 'destinations#index'

  resources :destinations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/destination.rb
class Destination < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :set_destination, only: [:show, :edit, :update, :destroy]

  # GET /destinations
  # GET /destinations.json
  def index
    @destinations = Destination.all
  end

  # GET /destinations/1
  # GET /destinations/1.json
  def show
  end

  # GET /destinations/new
  def new
    @destination = Destination.new
  end

  # GET /destinations/1/edit
  def edit
  end

  # POST /destinations
  # POST /destinations.json
  def create
    @destination = Destination.new(destination_params)

    respond_to do |format|
      if @destination.save
        format.html { redirect_to @destination, notice: 'Destination was successfully created.' }
        format.json { render :show, status: :created, location: @destination }
      else
        format.html { render :new }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /destinations/1
  # PATCH/PUT /destinations/1.json
  def update
    respond_to do |format|
      if @destination.update(destination_params)
        format.html { redirect_to @destination, notice: 'Destination was successfully updated.' }
        format.json { render :show, status: :ok, location: @destination }
      else
        format.html { render :edit }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /destinations/1
  # DELETE /destinations/1.json
  def destroy
    @destination.destroy
    respond_to do |format|
      format.html { redirect_to destinations_url, notice: 'Destination was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_destination
      @destination = Destination.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def destination_params
      params.require(:destination).permit(:city, :country, :latitude, :longitude)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/destinations/_form.html.erb
<%= form_with(model: destination, local: true) do |form| %>
  <% if destination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(destination.errors.count, "error") %> prohibited this destination from being saved:</h2>

      <ul>
      <% destination.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :destination_city %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country, id: :destination_country %>
  </div>

    <div class="field">
    <%= form.label :latitude %><br>
    <%= form.text_field :latitude %>
  </div>
   <div class="field">
    <%= form.label :longitude %><br>
    <%= form.text_field :longitude %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/destinations/edit.html.erb
<h1>Editing Destination</h1>

<%= render 'form', destination: @destination %>

<%= link_to 'Show', @destination %> |
<%= link_to 'Back', destinations_path %>

app/views/destinations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Destinations</h1>

<table>
  <thead>
    <tr>
      <th>City</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @destinations.each do |destination| %>
      <tr>
        <td><%= destination.city %></td>
        <td><%= destination.country %></td>
        <td><%= link_to 'Show', destination %></td>
        <td><%= link_to 'Edit', edit_destination_path(destination) %></td>
        <td><%= link_to 'Destroy', destination, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Destination', new_destination_path %>

app/views/destinations/new.html.erb
<h1>New Destination</h1>

<%= render 'form', destination: @destination %>

<%= link_to 'Back', destinations_path %>

app/views/destinations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>City:</strong>
  <%= @destination.city %>
</p>

<p>
  <strong>Country:</strong>
  <%= @destination.country %>
</p>

<p>
    <strong>Latitude and Longitude:</strong>
    <%= @destination.latitude %>, <%= @destination.longitude %>
</p>

<%= javascript_tag do %>
    var latitude = '<%= j @destination.latitude.to_s %>';
    var longitude = '<%= j @destination.longitude.to_s %>';
    var address = '<%= j @destination.city.to_s %>';
<% end %>




<div id="destination-map"></div>

<%= link_to 'Edit', edit_destination_path(@destination) %> |
<%= link_to 'Back', destinations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gmaps</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>

   <!-- Just before the closing body tag: <%= ENV['google_map_key'] %> is a figaro thang-->
    <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['google_map_key'] %>">
    </script>  
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
<h2>Google maps API demo</h2>
<div id="map-canvas"></div>